//  Auth - Signup
export const SIGNUP = "SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

//  Auth - Login
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

//  Auth - Logout
export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

//  Complete KYC
export const COMPLETE_KYC = "COMPLETE_KYC";
export const COMPLETE_KYC_SUCCESS = "COMPLETE_KYC_SUCCESS";
export const COMPLETE_KYC_FAILURE = "COMPLETE_KYC_FAILURE";

//  Complete KYC
export const ACCEPT_REJECT = "ACCEPT_REJECT";
export const ACCEPT_REJECT_SUCCESS = "ACCEPT_REJECT_SUCCESS";
export const ACCEPT_REJECT_FAILURE = "ACCEPT_REJECT_FAILURE";

//  Dashboard get balance
export const GET_BALANCE = "GET_BALANCE";
export const GET_BALANCE_SUCCESS = "GET_BALANCE_SUCCESS";
export const GET_BALANCE_FAILURE = "GET_BALANCE_FAILURE";

//  Dashboard get userdata
export const GET_USERDATA = "GET_USERDATA";
export const GET_USERDATA_SUCCESS = "GET_USERDATA_SUCCESS";
export const GET_USERDATA_FAILURE = "GET_USERDATA_FAILURE";

// Dashboard deposit to moneyplant
export const DEPOSIT_MONEYPLANT = "DEPOSIT_MONEYPLANT";
export const DEPOSIT_MONEYPLANT_SUCCESS = "DEPOSIT_MONEYPLANT_SUCCESS";
export const DEPOSIT_MONEYPLANT_FAILURE = "DEPOSIT_MONEYPLANT_FAILURE";

export const VERIFY_EMAIL = "VERIFY_EMAIL";
export const VERIFY_EMAIL_SUCCESS = "VERIFY_EMAIL_SUCCESS";
export const VERIFY_EMAIL_FAILURE = "VERIFY_EMAIL_FAILURE";

export const CRYPTO_PAYMENT = "RYPTO_PAYMENT";
export const CRYPTO_PAYMENT_SUCCESS = "CRYPTO_PAYMENT_SUCCESS";
export const CRYPTO_PAYMENT_FAILURE = "CRYPTO_PAYMENT_FAILURE";

export const ADD_NEW_ADDRESS = "ADD_NEW_ADDRESS";
export const ADD_NEW_ADDRESS_SUCCESS = "ADD_NEW_ADDRESS_SUCCESS";
export const ADD_NEW_ADDRESS_FAILURE = "ADD_NEW_ADDRESS_SUCCESS";

export const GET_ADDRESS_CARD = "GET_ADDRESS_CARD";
export const GET_ADDRESS_CARD_SUCCESS = "GET_ADDRESS_CARD_SUCCESS";
export const GET_ADDRESS_CARD_FAILURE = "GET_ADDRESS_CARD_FAILURE";

// Monumpay
export const MONUMPAY_DEPOSIT = "MONUMPAY_DEPOSIT";
export const MONUMPAY_DEPOSIT_SUCCESS = "MONUMPAY_DEPOSIT_SUCCESS";
export const MONUMPAY_DEPOSIT_FAILURE = "MONUMPAY_DEPOSIT_FAILURE";

export const MONUMPAY_WITHDRAWAL = "MONUMPAY_WITHDRAWAL";
export const MONUMPAY_WITHDRAWAL_SUCCESS = "MONUMPAY_WITHDRAWAL_SUCCESS";
export const MONUMPAY_WITHDRAWAL_FAILURE = "MONUMPAY_WITHDRAWAL_FAILURE";

export const MONUMPAY_WITHDRAWAL_REQUEST = "MONUMPAY_WITHDRAWAL_REQUEST";
export const MONUMPAY_WITHDRAWAL_REQUEST_SUCCESS =
  "MONUMPAY_WITHDRAWAL_REQUEST_SUCCESS";
export const MONUMPAY_WITHDRAWAL_REQUEST_FAILURE =
  "MONUMPAY_WITHDRAWAL_REQUEST_FAILURE";

export const BANK_WIRE_TRANSFER = "BANK_WIRE_TRANSFER";
export const BANK_WIRE_TRANSFER_SUCCESS = "BANK_WIRE_TRANSFER_SUCCESS";
export const BANK_WIRE_TRANSFER_FAILURE = "BANK_WIRE_TRANSFER_FAILURE";

export const NGENIUS_DEPOSIT = "NGENIUS_DEPOSIT";
export const NGENIUS_DEPOSIT_SUCCESS = "NGENIUS_DEPOSIT_SUCCESS";
export const NGENIUS_DEPOSIT_FAILURE = "NGENIUS_DEPOSIT_FAILURE";

export const EMAIL_WITHDRAW = "EMAIL_WITHDRAW";
export const EMAIL_WITHDRAW_SUCCESS = "EMAIL_WITHDRAW_SUCCESS";
export const EMAIL_WITHDRAW_FAILURE = "EMAIL_WITHDRAW_FAILURE";


